site_name: DigOutBox Documentation
theme: readthedocs
site_url: https://digoutbox.readthedocs.io
repo_url: https://github.com/galactic-forensics/DigOutBox
site_author: Reto Trappitsch

markdown_extensions:
  - admonition

plugins:
  - mermaid2

nav:
  - Home: index.md
  - Images: images.md
  - Versioning: versioning.md
  - Hardware: hardware.md
  - Firmware: firmware.md
  - Python Interface: cli.md
  - GUI: gui.md
  - Acknowledgement: acknowledgement.md
