# This workflow ensures that dummy and debug modes are turned off in all the files

name: mode_check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Build and test
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: controller
      run: |
        grep 'dummy: bool = False'  controller/src/controller/device_comm.py
    - name: controller_gui
      run: |
        grep 'self.dummy = False'  controller_gui/src/main/python/main.py
        grep 'self.debug = False'  controller_gui/src/main/python/main.py
    - name: firmware
      run: |
        grep 'const bool debug = false;' firmware/DigOutBox_fw*/config.h
        grep 'const bool EnableInterlock = false;' firmware/DigOutBox_fw*/config.h
