# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Build and test
  build:
    if: github.repository_owner == 'galactic-forensics'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: excitedleigh/setup-nox@v2.0.0
      run: |
        python -m pip install --upgrade pip
        nox
    - name: Install dependencies for coverage
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pytest-mock
        cd controller_cli
        pip install .
    - name: Run nox
      run: |
        cd controller_cli
        nox --no-error-on-missing-interpreters
    - name: Run pytest with coverage for report
      run:
        pytest --cov controller_cli
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
